- name: Add Nginx repository key
  apt_key:
      url: 'https://nginx.org/keys/nginx_signing.key'
      state: present

- name: Add Nginx mainline repository
  apt_repository:
      repo: deb https://nginx.org/packages/mainline/debian buster nginx
      state: present

- name: Install nginx
  apt:
    pkg:
      - nginx

- name: "Configure ssl by including ssl-cert{{ deployment_suffix }}.yml"
  include_tasks:
    file: "ssl-cert{{ deployment_suffix }}.yml"

- name: Open http port 80 for nginx
  ufw:
    rule: allow
    port: http

- name: Open https port 443 for nginx
  ufw:
    rule: allow
    port: https

- name: Allow TLSv1.2 and TLSv1.3 only. See https://blog.qualys.com/product-tech/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^\t*ssl_protocols'
    line: "\tssl_protocols TLSv1.2 TLSv1.3;  # Set by Ansible"

- name: Setup Nginx redirection HTTP -> HTTPS
  copy:
    src: always-https.conf
    dest: /etc/nginx/conf.d/always-https.conf
  notify:
    - nginx changed

- name: Remove Nginx default server config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - nginx changed
