- name: Instanciate rclone config
  template:
    src: rclone-b7.conf.j2
    dest: "{{ rclone_etc_dir }}/rclone-b7.conf"
    mode: 0400

- name: Copying auth key for Bâtiment 7
  copy:
    src: batiment7-714ee10f03d6.json
    dest: "{{ rclone_etc_dir }}"
    mode: 0400

- name: Copying rclone sync systemd service
  copy:
    src: rclone-b7.service
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Copying rclone sync systemd timer
  copy:
    src: rclone-b7.timer
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Register rclone sync timers
  systemd:
    name: rclone-b7.timer
    enabled: true
    state: started

- name: Copying rsync nextcloud systemd service
  copy:
    src: rsync-b7-nextcloud.service
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Copying rsync nextcloud systemd timer
  become: false
  copy:
    src: rsync-b7-nextcloud.timer
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Register rsync sync timers
  become: false
  systemd:
    name: rsync-b7-nextcloud.timer
    enabled: false

# nextcloud to gdrive migration

- name: Make migration scripts directory
  ansible.builtin.file:
    path: /home/pi/nc2gd/bin
    state: directory
    mode: '0755'

- name: Copy nc2gd.py
  ansible.builtin.copy:
    src: nc2gd.py
    dest: /home/pi/nc2gd/bin/nc2gd.py

- name: Copy nc2gd.sh
  ansible.builtin.copy:
    src: nc2gd.sh
    dest: /home/pi/nc2gd/bin/nc2gd.sh

