# nginx

- name: Install borg packages
  apt:
    pkg:
      - nginx

- name: Open port 80 for nginx
  ufw:
    rule: allow
    port: http

- name: Remove Nginx default server config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - "nginx changed"

- name: Copy grafana's nginx configuration file
  copy:
    src: nginx/grafana.conf  # TODO: move to files
    dest: /etc/nginx/sites-available/
  notify:
    - "nginx changed"

- name: Enable grafana's nginx configuration file
  file:
    src: /etc/nginx/sites-available/grafana.conf
    dest: /etc/nginx/sites-enabled/grafana.conf
    state: link
  notify:
    - "nginx changed"


# This guide has been useful in setting up InfluxDB / telegraf / grafaana
# https://www.howtoforge.com/tutorial/how-to-install-tig-stack-telegraf-influxdb-and-grafana-on-ubuntu-1804/

# Grafana

- name: Copying grafana logs dashboard
  copy:
    src: logs.json
    dest: /var/lib/grafana/dashboards/

- name: Execute cloudalchemy.grafana role
  include_role:
    name: cloudalchemy.grafana
  vars:
    grafana_security:
      admin_user: admin
      admin_password: admin  # TODO: replace and encrypt
    grafana_datasources:
      - name: telegraf
        type: influxdb
        url: 'http://localhost:8086'
        database: telegraf
      - name: loki
        type: loki
        url: 'http://localhost:3100'
    grafana_dashboards:
      - dashboard_id: 5955
        revision_id: 1
        datasource: telegraf

- name: Add InfluxDB / Telegraf repository key
  apt_key:
      url: 'https://repos.influxdata.com/influxdb.key'
      state: present

- name: Add InfluxDB / Telegraf Repository
  apt_repository:
      repo: 'deb https://repos.influxdata.com/debian buster stable'
      state: present

- name: Add Grafana repository key
  apt_key:
      url: 'https://packages.grafana.com/gpg.key'
      state: present

- name: Add Grafana Repository
  apt_repository:
      repo: 'deb https://packages.grafana.com/oss/deb stable main'
      state: present

- name: Install InfluxDB / Telegraf / Grafana
  apt:
    update_cache: yes
    pkg:
      - influxdb
      - telegraf
      - grafana

- name: Install telegraf.conf
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/
  notify:
    - "telegraf changed"

- name: Start InfluxDB
  systemd:
      name: influxdb
      enabled: true
      state: started

- name: Start telegraf
  systemd:
      name: telegraf
      enabled: true
      state: started

- name: Start Grafana
  systemd:
      name: grafana-server
      enabled: true
      state: started


# Loki

- name: Install unzip
  apt:
    pkg:
      - unzip

- name: Loki Download
  get_url:
      url: "https://github.com/grafana/loki/releases/download/v1.5.0/loki-linux-amd64.zip"
      checksum: sha256:00b4f134d8e54ce4dfb1ce71ffff3e5505202fa13625ec96cec75d44b816ed34
      dest: /tmp/loki-v1.5.0-linux-amd64.zip

- name: Unzip Loki
  unarchive:
      src: /tmp/loki-v1.5.0-linux-amd64.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: "a+x"

- name: Copying Loki systemd service config
  copy:
      src: loki.service
      dest: /etc/systemd/system/

- name: Copying Loki config
  copy:
      src: config-loki.yml
      dest: /usr/local/bin/

- name: Start Loki
  systemd:
      name: loki
      enabled: true
      state: started


# Promtail


- name: Promtail Download
  get_url:
      url: "https://github.com/grafana/loki/releases/download/v1.5.0/promtail-linux-amd64.zip"
      checksum: sha256:6695ea8d0c831c0ccab3abfac9e3bdf065e83887d540583b8e28644168ca038c
      dest: /tmp/promtail-v1.5.0-linux-amd64.zip

- name: Unzip Promtail
  unarchive:
      src: /tmp/promtail-v1.5.0-linux-amd64.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: "a+x"

- name: Copying Promtail service config
  copy:
      src: promtail.service
      dest: /etc/systemd/system/

- name: Copying promtail config
  copy:
      src: config-promtail.yml
      dest: /usr/local/bin/

- name: Start promtail
  systemd:
      name: promtail
      enabled: true
      state: started
