# nginx

- include_tasks:
    file: "main{{ deployment_suffix }}.yml"

- name: Instanciate grafana nginx config
  template:
    src: nginx/grafana.conf.j2
    dest: /etc/nginx/sites-available/grafana.conf
    mode: u=r,g=r,o=r
  notify:
    - "nginx changed"

- name: Enable grafana's nginx configuration file
  file:
    src: /etc/nginx/sites-available/grafana.conf
    dest: /etc/nginx/sites-enabled/grafana.conf
    state: link

# This guide has been useful in setting up InfluxDB / telegraf / grafana
# https://www.howtoforge.com/tutorial/how-to-install-tig-stack-telegraf-influxdb-and-grafana-on-ubuntu-1804/

# Grafana

- name: Add Grafana repository key
  apt_key:
      url: 'https://packages.grafana.com/gpg.key'
      state: present

- name: Add Grafana Repository
  apt_repository:
      repo: 'deb https://packages.grafana.com/oss/deb stable main'
      state: present

- name: Install grafana
  apt:
    update_cache: yes
    pkg:
      - grafana

- name: Instanciate grafana config
  template:
    src: grafana/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: u=rw,g=r
  notify:
    - "grafana changed"

- name: Copy grafana dashboards
  copy:
    src: grafana/dashboards/
    dest: /var/lib/grafana/dashboards/
    owner: root
    group: grafana
    mode: u=rw,g=r
  notify:
    - grafana changed

- name: Copy grafana provisioning files
  copy:
    src: grafana/provisioning/
    dest: /etc/grafana/provisioning/
    owner: root
    group: grafana
    mode: u=rw,g=r
    directory_mode: u=rwx,g=rx,o=rx
  notify:
    - grafana changed

- name: Start Grafana
  systemd:
      name: grafana-server
      enabled: true
      state: started


# Loki

- name: Install unzip
  apt:
    pkg:
      - unzip

- name: Loki Download
  get_url:
      url: "https://github.com/grafana/loki/releases/download/v2.2.0/loki-linux-amd64.zip"
      checksum: sha256:3d06f27e1e2ac5fa15261918bd14bb5da24988981634ea09855f8c67a3ba9ae3
      dest: /tmp/loki-v2.2.0-linux-amd64.zip

- name: Unzip Loki
  unarchive:
      src: /tmp/loki-v2.2.0-linux-amd64.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: "a+x"
  notify:
    - loki changed

- name: Copying Loki systemd service config
  copy:
      src: loki/loki.service
      dest: /etc/systemd/system/
  notify:
    - loki changed

- name: Copying Loki config
  copy:
      src: loki/config-loki.yml
      dest: /usr/local/bin/
  notify:
    - loki changed

- name: Start Loki
  systemd:
      name: loki
      enabled: true
      state: started


# Promtail


- name: Promtail Download
  get_url:
      url: "https://github.com/grafana/loki/releases/download/v2.2.0/promtail-linux-amd64.zip"
      checksum: sha256:8a0e1020381873b0111d7f6951c904e427271d4a9342adaa643c1580e23d31ec
      dest: /tmp/promtail-v2.2.0-linux-amd64.zip

- name: Unzip Promtail
  unarchive:
      src: /tmp/promtail-v2.2.0-linux-amd64.zip
      dest: /usr/local/bin/
      remote_src: yes
      mode: "a+x"
  notify:
    - promtail changed

- name: Copying Promtail service config
  copy:
      src: promtail/promtail.service
      dest: /etc/systemd/system/
  notify:
    - promtail changed

- name: Copying promtail config
  copy:
      src: promtail/config-promtail.yml
      dest: /usr/local/bin/
  notify:
    - promtail changed

- name: Start promtail
  systemd:
      name: promtail
      enabled: true
      state: started
