- name: "Setup common tools and VPN"
  hosts: servers
  become: true
  roles:
    - common
    - wireguard

- name: "Setup web applications"
  hosts: webservers
  become: true
  roles:
    - nginx
    - nginx-membres
    - grafana

- name: Setup dataproxies
  hosts: dataproxies
  become: true
  roles:
    - gdrivesync

- name: Setup borg repository stores
  hosts: borgstores
  become: true
  roles:
    - borgstore

- name: "Setup hosts to backup"
  hosts: "backuphead"
  become: true
  roles:
    - borgbackup
