- name: "Setup common tools and VPN"
  hosts: servers
  become: true
  roles:
    - systemd
    - common
    - wireguard

- name: Setup borg repository stores
  hosts: borgstores
  become: true
  roles:
    - borgstore

- name: "Setup hosts to backup"
  hosts: "backuphead"
  become: true
  roles:
    - systemd
    - borgbackup

- name: Setup dataproxies
  hosts: dataproxies
  become: true
  roles:
    - systemd
    - gdrivesync

- name: Setup influxdb
  hosts: webservers
  become: true
  roles:
    - influxdata-common
    - influxdata-influxdb

- name: Setup telegraf
  hosts: servers
  become: true
  roles:
    - influxdata-common
    - influxdata-telegraf

- name: "Setup web applications"
  hosts: webservers
  become: true
  roles:
    - systemd
    - nginx
    - nginx-membres
    - grafana
