- name: Copy grafana's nginx configuration file
  copy:
    src: ./files/nginx/grafana.conf
    dest: /etc/nginx/sites-available/

- name: Enable grafana's nginx configuration file
  file:
    src: /etc/nginx/sites-available/grafana.conf
    dest: /etc/nginx/sites-enabled/grafana.conf
    state: link

- name: Remove Nginx default server config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded

