- name: Install vouchers.epicerieledetour.org dependencies
  apt:
    pkg:
      - git
      - python3.7
      - sqlite3
      - virtualenv

- name: Copying vouchers.epicerieledetour.org systemd service file
  copy:
    src: ledetour-vouchers.service
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Copying vouchers.epicerieledetour.org backup systemd service file
  copy:
    src: ledetour-vouchers-backup.service
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Copying vouchers.epicerieledetour.org backup timer file
  copy:
    src: ledetour-vouchers-backup.timer
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Instanciating vouchers.epicerieledetour.org report systemd service file
  template:
    src: ledetour-vouchers-report.service.j2
    dest: /etc/systemd/system/ledetour-vouchers-report.service
    mode: u=r,g=r,o=
  notify:
    - systemd changed

- name: Copying vouchers.epicerieledetour.org report systemd timer file
  copy:
    src: ledetour-vouchers-report.timer
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Stop vouchers.epicerieledetour.org systemd service
  systemd:
    name: ledetour-vouchers.service
    state: stopped

- name: Create www-data owned /var/www/ledetour-vouchers
  ansible.builtin.file:
    path: /var/www/ledetour-vouchers
    owner: www-data
    group: www-data
    state: directory

- name: Create www-data owned /var/www/ledetour-vouchers/reports
  ansible.builtin.file:
    path: /var/www/ledetour-vouchers
    owner: www-data
    group: www-data
    state: directory

- name: Create www-data owned /var/run/ledetour-vouchers
  ansible.builtin.file:
    path: /var/run/ledetour-vouchers
    owner: www-data
    group: www-data
    state: directory

- name: Install vouchers.epicerieledetour.org
  ansible.builtin.pip:
    name: git+https://github.com/epicerieledetour/ledetour-vouchers.git
    virtualenv_python: python3.7
    virtualenv: /var/www/ledetour-vouchers/venv-py37
    state: forcereinstall

- include_tasks:
    file: "main{{ deployment_suffix }}.yml"  

- name: Instanciate vouchers nginx config
  template:
    src: vouchers.conf.j2
    dest: /etc/nginx/sites-available/vouchers.conf
    mode: u=r,g=r,o=r
  notify:
    - nginx changed

- name: Enable vouchers.epicerieledetour.org nginx configuration file
  file:
    src: /etc/nginx/sites-available/vouchers.conf
    dest: /etc/nginx/sites-enabled/vouchers.conf
    state: link

- name: Enable vouchers.epicerieledetour.org systemd service
  systemd:
    name: ledetour-vouchers.service
    state: started
    enabled: yes

- name: Enable vouchers.epicerieledetour.org backup systemd timer
  systemd:
    name: ledetour-vouchers-backup.timer
    state: started
    enabled: yes

- name: Enable vouchers.epicerieledetour.org report systemd timer
  systemd:
    name: ledetour-vouchers-report.timer
    state: started
    enabled: yes
