- name: Install borg packages
  apt:
    pkg:
      - borgbackup

# Static configuration

- name: Copying backup script
  copy:
    src: backup.sh
    dest: /usr/local/bin/
    mode: 0500

- name: Make /usr/local/etc/borg directory
  file:
    path: /usr/local/etc/borg
    state: directory
    mode: 0700

- name: Copying backup script systemd service file
  copy:
    src: backup@.service
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Copying backup script systemd timer file
  copy:
    src: backup@.timer
    dest: /etc/systemd/system/
  notify:
    - systemd changed

# Dynamic configuration per borgstore host in inventory

- name: "Generate an ssh keypair for borg stores"
  openssh_keypair:
    path: /usr/local/etc/borg/id_ssh_rsa
    comment: "{{ inventory_hostname }} borg"
    mode: 0400
  register: borg_ssh

- name: "Configure borg backup stores"
  include_tasks:
    file: store.yml
  loop: "{{ groups['borgstores'] }}"
  vars:
    borg_store_host: "{{ hostvars[item].wireguard_address }}"
    borg_store_name: "{{ item }}"
    borg_store_user: "{{ hostvars[item].ansible_user }}"
    borg_repo_name: "{{ inventory_hostname }}"
    borg_repo: "{{ borg_store_user }}@{{ borg_store_host }}:/srv/borg/{{ inventory_hostname }}"
