- name: Install borg packages
  apt:
    pkg:
      - borgbackup

- name: Setting up Borg passphrase in /etc/environment
  # TODO: remove BORG_PASSPHRASE from /etc/environment
  lineinfile:
    path: /etc/environment
    insertafter: EOF
    line: "export BORG_PASSPHRASE='{{ borg_passphrase }}'"

- name: Setup backup repository
  # TODO: loop through borg-repository groups and init them with ssh
  command: 'borg init --encryption=repokey /home/backup/'
  args:
    creates: /home/backup  # TODO: move to /var/backups
  environment:
    BORG_PASSPHRASE: "{{ borg_passphrase }}"

- name: Copying backup script
  copy:
    src: backup.sh
    dest: /usr/local/bin/backup/  # TODO: install to /usr/local/bin
    mode: a+x

- name: Copying backup script systemd service file
  copy:
    src: backup.service
    dest: /etc/systemd/system/

- name: Copying backup script systemd timer file
  copy:
    src: backup.timer
    dest: /etc/systemd/system/

- name: Start backup script timer
  systemd:
    name: backup.timer
    enabled: true
    state: started
