wireguard_type: client
wireguard_address: 192.168.211.40
wireguard_private_key: "{{ vault_wireguard_private_key }}"
wireguard_public_key: "fvHCkUlAKAbNeIBGWM0m4zoxHS9y7kkkc2snGpryYFw="
wireguard_endpoint_port: 51820
