- name: Ensure hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Setup charlesfleches keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXtNPFg0j1Ssd+CwUF0enPqTR3OuEb4WU2DlwNuLsgpTv13dXNFvF44/hnk5d9FxvJOfR/B7buUf4GkVvLgsr25k/nRAU0riY16L1WOM2chjQ8CsByuIzhmkWQEcz2QKvrSLmgU5jNSegUWTjwbKeslHnAptmEMA9QkQaQzCTMTqM6Z6oUx2N72VyG2ZZtXUUUEJL5JzpZV/DoSj/sFuTwegOUjfv6Fn8KXDHPxrigrqKi0ssPPYpUe1U/Xr86/qv1kR3JlDw+zUdn0mV9QzKMOo42kYbM7ShDQg6b61P6I3lJXZGitgkB8rh4wwy/Yz01HutyGAMSdVwtMUt9RSRR charles@charles-xps15

- name: Setup mauriandres keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUP3E8D6oMeIAYllmkz3/WoK6MtupfojMijxXzbEe/FdIBgI/Vdt350LWaQUDmXlbqIBMQwe0TLYQ4DYBktEmAntYGo/YkJI/MxEzXvwkKYKz9zT7RSL/fP0GMPUuJpR6VXSgI9M4mHBwSaCSaFELe5dVdv3veEs0cHUTenMkitrJmDoXTXmqfppplRqfUBXCFH3u6/TOsdZMh2797iru9efVhJsvwFEogc153yIyVdPM7unhKLGN4mKJ/eq7ZBr4hifMNfV4pk+Qf4TmNpw/mMvXUTqaEQRTSYk2TtAGSprsRk5lqJHx2jamtfqbH4AR/ydJISeyKuGToUIf7HVEQ7OuC9KmWVilp3a4o2dRH0lrCJcW9A/qC1SPr317jyQWFUMbjVDT3AXdyCTrxv6DsJ6SaoTgq2BzkGIQz71EuzUqWfug5KM8rOwLBsvtIdkkc06kUJWcyggDst6/oICi87vh8+S1GGxCCKfoMZgJD39cLX/pLN7Car9WgmnaHS6BFWJxV+TG4txIrxNTa+wleuD9Yb6Pk2f+1iaBIc48QEFccHpgI3TKmuM1UDSYFlZc6TM5+502hgvifXDLIdAqYrkLZDv22rrl1odA2z52eG4fGgMLVbsQtbu2kC1KygSPeUFn/rwCglCdhAHrWEU5n0wAsX5qUmt6T/nQ5cISVFw==

- name: Setup Wmbat keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC6CEiSkgXyxDd5GYUl/e7MsgTdXwBXBE7hLO145wXZoak5c6CUyRDs0iTJhqVEI4HO/TcngtC44vApSNYH3RkeHmPiSDwukqTfBh4bvmrtpGTTaYT2Iz0sM14Ey1O47puBb5nuXQc2T1u7P1YxV9IqNRPQ8ZWIR7HoOioZazAaGUK0+WI+RICmDW6lY3ViJXZfxKH12C9b+QHSfpg/pzFCLx5KEKTB509+eSq7kfrwh/JrZ2K7NMy9HSWMYL/G3KLByWU8H5fooLvpeq6v5+gyrKYgflXLzP722YA90Tt6RQj+0zcQulgacrhEFuGt1I2CMNy9kwR1/sx3ZKlxcvi+Q9gHhBq5YQiP3Cci10QqgAwA+ErVtV3VsnBSbhbypkeVh7UEBdMPnx4eV/Z24Uiy/MQkrtmenOkqp/diD2aTFWZam8xsIAuT//hgnbkMdEL5T//yG/cNc4tpTRZVRwP/y6I766afXLZ6O3ZFYa40HHMQK7W3QK08ndVsYRG70l1zHeuTskyszeVqdDG2Fas8UF1ajazIXf1XO/QCMXFxs6k4g0Bl5PWXDe2mCf2uRSf8T4COq3jxhNhIb693e9nz1ziiad/IekgrvAKdigE+zIpb102AJcivbSyvID5BXzUcyxbNDGFv2KAHNBKsNwBrgIkggel8678fbmRgIiRJ4Q==

- name: Update apt cache
  apt:
    update_cache: yes

# We install common packages before an upgrade as unattended-upgrades
# may set /var/run/reboot-required, which will be needed in case the
# upgrade installs a new kernel
- name: Install common packages
  apt:
    pkg:
      - aptitude
      - fail2ban
      - python3
      - unattended-upgrades
      - ufw
      - vim

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Check if a reboot is required
  register: rebootrequired
  stat:
    path: /var/run/reboot-required
    get_md5: no

- name: Reboot if /var/run/reboot-required exists
  reboot:
  when: rebootrequired.stat.exists == true

- name: Activate unattended-upgrades
  block:
    - name: Update debconf parameters
      debconf:
        name: 'unattended-upgrades'
        question: 'unattended-upgrades/enable_auto_updates'
        value: 'true'
        vtype: 'boolean'

    - name: Reconfigure dpkg
      command: dpkg-reconfigure -f noninteractive unattended-upgrades creates=/etc/apt/apt.conf.d/20auto-upgrades

    - name: Remove non-security upgrades
      lineinfile:
          path: /etc/apt/apt.conf.d/50unattended-upgrades
          regexp: 'label=Debian";'
          state: absent

- name: Disable all ports but ssh
  ufw:
    state: enabled
    policy: deny
    rule: allow
    port: '22'
