- name: Reload grafana
  systemd:
    name: grafana-server
    state: restarted
  listen: "grafana changed"

- name: Reload loki
  systemd:
    name: loki
    state: restarted
  listen: "loki changed"

- name: Reload promtail
  systemd:
    name: promtail
    state: restarted
  listen: "promtail changed"
