# TODO: use apt_repository
- name: Copy /etc/apt/sources.list.d/buster-backports.list
  copy:
    src: buster-backports.list
    dest: /etc/apt/sources.list.d

- name: Install wireguard
  apt:
    pkg:
      - linux-headers-cloud-amd64  # HACK: `cloud-amd` should be gathered as a fact
      - wireguard
    update_cache: true
    state: present

- name: Instanciate wireguard config
  template:
    src: wg-ledetour-{{ wireguard_type }}.conf.j2
    dest: /etc/wireguard/wg-ledetour.conf
    mode: u=r,g=,o=
  notify:
    - reload wireguard

- name: Open wireguard port
  ufw:
    rule: allow
    proto: udp
    port: '"{{ wireguard_endpoint_port }}"'

- name: Start wireguard systemd service wg-quick@wg-ledetour.service
  systemd:
    name: wg-quick@wg-ledetour.service
    enabled: yes
    state: started
