- name: "Setting wireguard_conf_path"
  set_fact:
    wireguard_conf_path: "wg-ledetour.conf-{{ ansible_host }}"

- name: Instanciate wireguard config {{ wireguard_conf_path }}
  template:
    src: wg-ledetour-{{ wireguard_type }}.conf.j2
    dest: "{{ wireguard_conf_path }}"
    mode: u=r,g=,o=

- name: "Wireguard info"
  debug:
   msg:
     - "Created wireguard config file {{ wireguard_conf_path }}"
     - "Install it as root with `mv {{ wireguard_conf_path }} /etc/wireguard/wg-ledetour.conf`"
     - "Activate wireguard with:"
     - "- Either directly with wg-quick `wg-quick up wg-ledetour`"
     - "- Or with systemd `sysemctl start wg-quick@wg-ledetour.service`"
     - "Don't forget to open your firewall: UDP outbound port {{ wireguard_endpoint_port }}"
