- name: Install gdrivesync packages
  apt:
    pkg:
      - rclone

- name: Copying Google Drive sync script
  copy:
    src: gdrive-sync.sh
    dest: /usr/local/bin/gdrive/  # TODO: move to /usr/local/bin
    mode: a+x

- name: Copying google drive sync script systemd service
  copy:
    src: gdrive-sync.service
    dest: /etc/systemd/system/

- name: Copying google drive sync script systemd timer
  copy:
    src: gdrive-sync.timer
    dest: /etc/systemd/system/

- name: Copying rclone configuration
  copy:
    src: rclone.conf
    dest: /home/gdrive/

- name: Copying auth
  copy:
    src: credentials.json
    dest: /home/gdrive/

- name: Start Google drive backup script
  systemd:
      name: "gdrive-sync.timer"
      enabled: true
      state: started
