- name: Install rclone
  apt:
    deb: https://downloads.rclone.org/v1.59.2/rclone-v1.59.2-linux-arm64.deb

- name: Make /usr/local/etc/rclone directory
  file:
    path: /usr/local/etc/rclone
    state: directory
    mode: 0700

- name: Instanciate rclone config
  template:
    src: rclone.conf.j2
    dest: /usr/local/etc/rclone/rclone.conf
    mode: 0400

- name: Copying auth
  copy:
    src: drive-sync-on-ovh-server-50a335a0b68b.json
    dest:  /usr/local/etc/rclone/
    mode: 0400

- name: Make /srv/rclone directory
  file:
    path: /srv/rclone
    state: directory
    mode: 0700

- name: Copying google drive sync script systemd service
  copy:
    src: rclone-drive@.service
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Copying google drive sync script systemd timer
  copy:
    src: rclone-drive@.timer
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Register Drive sync timers
  systemd:
    name: "rclone-drive@{{ item.name }}.timer"
    enabled: true
    state: started
  loop: "{{ google_drives }}"

- name: Register B7-NEXTCLOUD sync timers
  systemd:
    name: "rclone-drive@B7-NEXTCLOUD.timer"
    enabled: true
    state: started
