- name: Install rclone
  apt:
    deb: https://downloads.rclone.org/v1.59.2/rclone-v1.59.2-linux-arm64.deb

- name: Make /usr/local/etc/rclone directory
  file:
    path: /usr/local/etc/rclone
    state: directory
    mode: 0700

- name: Instanciate rclone config
  template:
    src: rclone.conf.j2
    dest: /usr/local/etc/rclone/rclone.conf
    mode: 0400

- name: Copying auth key for Le Détours Google Drives 
  copy:
    src: drive-sync-on-ovh-server-50a335a0b68b.json
    dest: "{{ rclone_etc_dir }}"
    mode: 0400

- name: Copying auth key for Bâtiment 7
  copy:
    src: batiment7-714ee10f03d6.json
    dest: "{{ rclone_etc_dir }}"
    mode: 0400

- name: Make /srv/rclone directory
  file:
    path: /srv/rclone
    state: directory
    mode: 0700

- name: Copying rclone sync systemd service
  copy:
    src: rclone-alldrives.service
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Copying rclone sync systemd timer
  copy:
    src: rclone-alldrives.timer
    dest: /etc/systemd/system/
  notify:
    - systemd changed

- name: Register rclone sync timers
  systemd:
    name: rclone-alldrives.timer
    enabled: true
    state: started
