- name: Install gdrivesync packages
  apt:
    pkg:
      - rclone

- name: Copying Google Drive sync script
  copy:
    src: gdrive-sync.sh
    dest: /usr/local/bin
    mode: a+x

- name: Copying google drive sync script systemd service
  copy:
    src: gdrive-sync.service
    dest: /etc/systemd/system/

- name: Copying google drive sync script systemd timer
  copy:
    src: gdrive-sync.timer
    dest: /etc/systemd/system/

- name: Copying rclone configuration
  copy:
    src: rclone.conf
    dest: /usr/local/etc/rclone/

- name: Copying auth
  copy:
    src: credentials.json
    dest:  /usr/local/etc/rclone/
    mode: 0400

- name: Make /srv/rclone/gdrive-sync directory
  file:
    path: /srv/rclone/gdrive-sync
    state: directory
    mode: 0700

- name: Start Google drive backup script
  systemd:
      name: gdrive-sync.timer
      enabled: true
      state: started
